### PR TITLE
Add core-js for old browser compatibility

### PR DESCRIPTION
**Pull request by TuoLuo994**
core-js automatically transpiles into ie 11 compatible code

### CODE REVIEW

**Comment by TuoLuo994** [comment]
@Shandorin please test and merge if it works for you.

**Comment by Shandorin** [comment]
Monthview styling breaks when used on ie 11. Dayview doesn't load properly and always goes to current date

**Comment by TuoLuo994** [comment]
Old browser warning works now so only weekview and monthview working is acceptable. Merging.

**Comment by TuoLuo994** [comment]
Breaks everything, out of scope for now.

**Pull request closed without merging**
