### PR TITLE
Reduce api calls - Week and freeform daterange

### PR DESCRIPTION
**Pull request by Liljenmaa**
This push introduces the week and freeform daterange for the week and month view. Any other views could also be implemented with the freeform daterange.

The following non-blocking "problems" a.k.a. differences to the original version still exist:

Any supervisor absent day (white) will neither contain the Schedule ID of the range nor any related track records for the day.
Any range closed day (red) will neither contain the Reservation ID of the range nor any related track records for the day. 

These things seem to logically make sense not to be there: I'm not sure whether some function actually uses these values though.

Neither of these problems seem to cause any harm. Please notify if they do.

### CODE REVIEW

**Comment by TuoLuo994** [comment]
node_modules should not be added to repo. Maybe .gitignore not working properly?

**Comment by TuoLuo994** [comment]
I don't know why but after changing things in /scheduling, the weekdays get messed up
image

**Comment by Liljenmaa** [comment]
Thanks. Fixed all the issues mentioned.

**Review by Shandorin — APPROVED** [review]
Looks good. didn't notice any errors

**Comment by TuoLuo994** [comment]
Looks. good. Please fix these linting errors in controllers/daterange.js before merge
```
9:50  error  Missing semicolon                 semi                                                       20:5   error  'fieldModifiedQR' is not defined  no-undef
22:36  error  'i' is defined but never used     no-unused-vars                                             23:21  error  'fieldModifiedQR' is not defined  no-undef
28:9   error  'fieldModifiedQR' is not defined  no-undef                                                   29:9   error  'fieldModifiedQR' is not defined  no-undef
29:25  error  'fieldModifiedQR' is not defined  no-undef                                                   43:11  error  Missing semicolon                 semi
47:7   error  'fieldModifiedQR' is not defined  no-undef                                                   58:61  error  Strings must use singlequote      quotes
61:9   error  Missing semicolon                 semi                                                       64:5   error  'finalQR' is not defined          no-undef
66:5   error  'fieldModifiedQR' is not defined  no-undef                                                   67:7   error  'finalQR' is not defined          no-undef
73:86  error  Strings must use singlequote      quotes                                                     79:8   error  Missing semicolon                 semi
82:5   error  'finalQR' is not defined          no-undef                                                   91:13  error  'finalQR' is not defined          no-undef
```

**Pull request merged**
